#Name of the workflow
name: Code
#When the WF should run
on: 
   push:
#Jobs in the WF
jobs:
   code-checkout:
   runs-onn: ubuntu-latest
   #Steps in the WF 
   steps:
   -name : Clone the code
   uses: actions/checkout@v7

   -name: print the message
   run: echo "Code Cloned"
