# Name of the workflow
name: Code

# When the workflow should run
on:
  workflow_call: 

# Jobs in the workflow
jobs:
  code-checkout:
    runs-on: ubuntu-latest

    # Steps in the workflow
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Print the message
        run: echo "Code Cloned"
